name: doc
on:
  push:
    branches:
      - docs
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: username/repo
        TARGET_BRANCH: master
        BUILD_SCRIPT: cd docs && yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://slyr.north-road.com

